apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 5Gi         # 이 볼륨의 크기는 5G입니다.
  accessModes:
    - ReadWriteOnce    # 하나의 pod나 인스턴스에 의해서만 마운트
  awsElasticBlockStore:
    fsType: ext4
    volumeID: <볼륨아이디>